/* Generated by gbrecomp from Pinball - Revenge of the 'Gator (USA, Europe) */
#include "Pinball___Revenge_of_the__Gator__USA__Europe__internal.h"
#include "gbrt.h"
#include <stdio.h>
#include <stdlib.h>

/* Bank dispatch - routes calls to the correct bank function */
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_00(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_01(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_02(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_03(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_04(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_05(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_06(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_07(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_08(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_09(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_10(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_11(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_12(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_13(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_14(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_15(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_16(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_17(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_18(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_19(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_20(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_21(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_22(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_23(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_24(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_25(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_26(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_27(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_28(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_29(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_30(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_31(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_32(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_33(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_34(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_35(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_36(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_37(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_38(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_39(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_40(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_41(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_42(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_43(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_44(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_45(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_46(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_47(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_48(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_49(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_50(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_51(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_52(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_53(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_54(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_55(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_56(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_57(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_58(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_59(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_60(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_61(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_62(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_63(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_64(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_65(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_66(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_67(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_68(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_69(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_70(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_71(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_72(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_73(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_74(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_75(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_76(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_77(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_78(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_79(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(GBContext* ctx, uint16_t addr, uint16_t bank);

static uint8_t ram_overlay_0_matches(GBContext* ctx) {
    if (gb_read8(ctx, 0xff80) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff81) != 0xc0) return 0;
    if (gb_read8(ctx, 0xff82) != 0xe0) return 0;
    if (gb_read8(ctx, 0xff83) != 0x46) return 0;
    if (gb_read8(ctx, 0xff84) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff85) != 0x28) return 0;
    if (gb_read8(ctx, 0xff86) != 0x3d) return 0;
    if (gb_read8(ctx, 0xff87) != 0x20) return 0;
    if (gb_read8(ctx, 0xff88) != 0xfd) return 0;
    if (gb_read8(ctx, 0xff89) != 0xc9) return 0;
    return 1;
}

static uint8_t try_dispatch_compiled_ram_overlay(GBContext* ctx, uint16_t addr, uint16_t bank) {
    if (addr >= 0xff80 && addr < 0xff8a) {
        if (!ram_overlay_0_matches(ctx)) {
            return 0;
        }
        switch (addr) {
            case 0xff80:
                Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff82:
                Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff84:
                Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff86:
                Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff87:
                Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff89:
                Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank);
                return 1;
            default:
                return 0;
        }
    }
    return 0;
}

void gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped && !ctx->halted) {
        gbrt_note_generated_indirect_dispatch(ctx);
        addr = ctx->pc;
        uint16_t bank = gb_resolve_rom_bank(ctx, addr);
        if (gbrt_instruction_limit > 0) {
            if (gbrt_instruction_count >= gbrt_instruction_limit) {
                fprintf(stderr, "[LIMIT] Reached instruction limit %llu\n", (unsigned long long)gbrt_instruction_limit);
                exit(0);
            }
            gbrt_instruction_count++;
        }
        if (ctx->trace_entries_enabled) gbrt_log_trace(ctx, bank, addr);
        if (gbrt_trace_enabled) {
            fprintf(stderr, "[TRACE] Dispatch 0x%04X (Bank %d)\n", addr, bank);
        }
        if (gbrt_try_execute_hram_stub(ctx, addr)) {
            if (ctx->single_step_mode) break;
            continue;
        }
        if (gbrt_try_execute_highmem_stub(ctx, addr)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (gbrt_try_execute_ram_stub(ctx, addr)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (try_dispatch_compiled_ram_overlay(ctx, addr, bank)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (addr >= 0xFF80 && addr <= 0xFFFE) {
            gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_WRITABLE_HRAM, 0);
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        switch (addr >> 8) {
            case 0x00: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_00(ctx, addr, bank); break;
            case 0x01: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_01(ctx, addr, bank); break;
            case 0x02: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_02(ctx, addr, bank); break;
            case 0x03: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_03(ctx, addr, bank); break;
            case 0x04: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_04(ctx, addr, bank); break;
            case 0x05: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_05(ctx, addr, bank); break;
            case 0x06: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_06(ctx, addr, bank); break;
            case 0x07: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_07(ctx, addr, bank); break;
            case 0x08: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_08(ctx, addr, bank); break;
            case 0x09: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_09(ctx, addr, bank); break;
            case 0x0a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0a(ctx, addr, bank); break;
            case 0x0b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0b(ctx, addr, bank); break;
            case 0x0c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0c(ctx, addr, bank); break;
            case 0x0d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0d(ctx, addr, bank); break;
            case 0x0e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0e(ctx, addr, bank); break;
            case 0x0f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_0f(ctx, addr, bank); break;
            case 0x10: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_10(ctx, addr, bank); break;
            case 0x11: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_11(ctx, addr, bank); break;
            case 0x12: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_12(ctx, addr, bank); break;
            case 0x13: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_13(ctx, addr, bank); break;
            case 0x14: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_14(ctx, addr, bank); break;
            case 0x15: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_15(ctx, addr, bank); break;
            case 0x16: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_16(ctx, addr, bank); break;
            case 0x17: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_17(ctx, addr, bank); break;
            case 0x18: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_18(ctx, addr, bank); break;
            case 0x19: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_19(ctx, addr, bank); break;
            case 0x1a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1a(ctx, addr, bank); break;
            case 0x1b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1b(ctx, addr, bank); break;
            case 0x1c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1c(ctx, addr, bank); break;
            case 0x1d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1d(ctx, addr, bank); break;
            case 0x1e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1e(ctx, addr, bank); break;
            case 0x1f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_1f(ctx, addr, bank); break;
            case 0x20: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_20(ctx, addr, bank); break;
            case 0x21: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_21(ctx, addr, bank); break;
            case 0x22: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_22(ctx, addr, bank); break;
            case 0x23: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_23(ctx, addr, bank); break;
            case 0x24: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_24(ctx, addr, bank); break;
            case 0x25: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_25(ctx, addr, bank); break;
            case 0x26: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_26(ctx, addr, bank); break;
            case 0x27: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_27(ctx, addr, bank); break;
            case 0x28: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_28(ctx, addr, bank); break;
            case 0x29: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_29(ctx, addr, bank); break;
            case 0x2a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2a(ctx, addr, bank); break;
            case 0x2b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2b(ctx, addr, bank); break;
            case 0x2c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2c(ctx, addr, bank); break;
            case 0x2d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2d(ctx, addr, bank); break;
            case 0x2e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2e(ctx, addr, bank); break;
            case 0x2f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_2f(ctx, addr, bank); break;
            case 0x30: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_30(ctx, addr, bank); break;
            case 0x31: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_31(ctx, addr, bank); break;
            case 0x32: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_32(ctx, addr, bank); break;
            case 0x33: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_33(ctx, addr, bank); break;
            case 0x34: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_34(ctx, addr, bank); break;
            case 0x35: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_35(ctx, addr, bank); break;
            case 0x36: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_36(ctx, addr, bank); break;
            case 0x37: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_37(ctx, addr, bank); break;
            case 0x38: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_38(ctx, addr, bank); break;
            case 0x39: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_39(ctx, addr, bank); break;
            case 0x3a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3a(ctx, addr, bank); break;
            case 0x3b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3b(ctx, addr, bank); break;
            case 0x3c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3c(ctx, addr, bank); break;
            case 0x3d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3d(ctx, addr, bank); break;
            case 0x3e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3e(ctx, addr, bank); break;
            case 0x3f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_3f(ctx, addr, bank); break;
            case 0x40: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_40(ctx, addr, bank); break;
            case 0x41: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_41(ctx, addr, bank); break;
            case 0x42: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_42(ctx, addr, bank); break;
            case 0x43: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_43(ctx, addr, bank); break;
            case 0x44: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_44(ctx, addr, bank); break;
            case 0x45: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_45(ctx, addr, bank); break;
            case 0x46: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_46(ctx, addr, bank); break;
            case 0x47: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_47(ctx, addr, bank); break;
            case 0x48: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_48(ctx, addr, bank); break;
            case 0x49: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_49(ctx, addr, bank); break;
            case 0x4a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4a(ctx, addr, bank); break;
            case 0x4b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4b(ctx, addr, bank); break;
            case 0x4c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4c(ctx, addr, bank); break;
            case 0x4d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4d(ctx, addr, bank); break;
            case 0x4e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4e(ctx, addr, bank); break;
            case 0x4f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_4f(ctx, addr, bank); break;
            case 0x50: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_50(ctx, addr, bank); break;
            case 0x51: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_51(ctx, addr, bank); break;
            case 0x52: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_52(ctx, addr, bank); break;
            case 0x53: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_53(ctx, addr, bank); break;
            case 0x54: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_54(ctx, addr, bank); break;
            case 0x55: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_55(ctx, addr, bank); break;
            case 0x56: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_56(ctx, addr, bank); break;
            case 0x57: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_57(ctx, addr, bank); break;
            case 0x58: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_58(ctx, addr, bank); break;
            case 0x59: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_59(ctx, addr, bank); break;
            case 0x5a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5a(ctx, addr, bank); break;
            case 0x5b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5b(ctx, addr, bank); break;
            case 0x5c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5c(ctx, addr, bank); break;
            case 0x5d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5d(ctx, addr, bank); break;
            case 0x5e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5e(ctx, addr, bank); break;
            case 0x5f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_5f(ctx, addr, bank); break;
            case 0x60: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_60(ctx, addr, bank); break;
            case 0x61: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_61(ctx, addr, bank); break;
            case 0x62: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_62(ctx, addr, bank); break;
            case 0x63: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_63(ctx, addr, bank); break;
            case 0x64: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_64(ctx, addr, bank); break;
            case 0x65: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_65(ctx, addr, bank); break;
            case 0x66: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_66(ctx, addr, bank); break;
            case 0x67: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_67(ctx, addr, bank); break;
            case 0x68: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_68(ctx, addr, bank); break;
            case 0x69: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_69(ctx, addr, bank); break;
            case 0x6a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6a(ctx, addr, bank); break;
            case 0x6b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6b(ctx, addr, bank); break;
            case 0x6c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6c(ctx, addr, bank); break;
            case 0x6d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6d(ctx, addr, bank); break;
            case 0x6e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6e(ctx, addr, bank); break;
            case 0x6f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_6f(ctx, addr, bank); break;
            case 0x70: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_70(ctx, addr, bank); break;
            case 0x71: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_71(ctx, addr, bank); break;
            case 0x72: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_72(ctx, addr, bank); break;
            case 0x73: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_73(ctx, addr, bank); break;
            case 0x74: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_74(ctx, addr, bank); break;
            case 0x75: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_75(ctx, addr, bank); break;
            case 0x76: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_76(ctx, addr, bank); break;
            case 0x77: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_77(ctx, addr, bank); break;
            case 0x78: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_78(ctx, addr, bank); break;
            case 0x79: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_79(ctx, addr, bank); break;
            case 0x7a: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7a(ctx, addr, bank); break;
            case 0x7b: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7b(ctx, addr, bank); break;
            case 0x7c: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7c(ctx, addr, bank); break;
            case 0x7d: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7d(ctx, addr, bank); break;
            case 0x7e: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7e(ctx, addr, bank); break;
            case 0x7f: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_7f(ctx, addr, bank); break;
            case 0xff: Pinball___Revenge_of_the__Gator__USA__Europe__dispatch_ff(ctx, addr, bank); break;
            default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_PAGE_NOT_COMPILED, 0); break;
        }
        if (ctx->single_step_mode) break;
    }
}

void gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    gb_dispatch(ctx, addr);
}

const GBConfig* Pinball___Revenge_of_the__Gator__USA__Europe__default_config(void) {
    static const GBConfig config = {
        .model = GB_MODEL_DMG,
        .cgb_compatibility_mode = false,
        .cartridge_supports_cgb = false,
        .cartridge_requires_cgb = false,
        .enable_bootrom = false,
        .enable_audio = true,
        .enable_serial = true,
        .speed_percent = 100,
        .native_presentation_enabled = false,
    };
    return &config;
}

void Pinball___Revenge_of_the__Gator__USA__Europe__init(GBContext* ctx, const uint8_t* rom_data, size_t rom_size) {
    gb_context_load_rom(ctx, rom_data, rom_size);
    gb_context_reset(ctx, true);
}

void Pinball___Revenge_of_the__Gator__USA__Europe__run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    gb_dispatch(ctx, ctx->pc);
}
