/* Generated by gbrecomp */
#ifndef Pinball___Revenge_of_the__Gator__USA__Europe__H
#define Pinball___Revenge_of_the__Gator__USA__Europe__H

#include "gbrt.h"

const GBConfig* Pinball___Revenge_of_the__Gator__USA__Europe__default_config(void);
void Pinball___Revenge_of_the__Gator__USA__Europe__run(GBContext* ctx);
void Pinball___Revenge_of_the__Gator__USA__Europe__init(GBContext* ctx, const uint8_t* rom_data, size_t rom_size);
int Pinball___Revenge_of_the__Gator__USA__Europe__main(int argc, char* argv[]);

#endif
